package com.textbot.translator;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.provider.Settings;import android.util.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.util.concurrent.atomic.AtomicBoolean;
public class ScreenCaptureService extends Service{
 public interface FrameListener{void onFrame(String data);} private static volatile FrameListener listener;private static volatile ScreenCaptureService instance;
 private MediaProjection projection;private VirtualDisplay display;private ImageReader reader;private HandlerThread thread;private Handler handler;private final AtomicBoolean requested=new AtomicBoolean(false);private int w,h,dpi;private WindowManager wm;private View overlay;private TextView status;
 public static void setFrameListener(FrameListener l){listener=l;}public static boolean isRunning(){return instance!=null;}public static void requestFrame(){if(instance!=null)instance.requested.set(true);}
 @Override public void onCreate(){super.onCreate();instance=this;channel();Notification n=new Notification.Builder(this,"capture").setContentTitle("TextBot 화면 번역").setContentText("화면 위 번역 UI 실행 중").setSmallIcon(R.drawable.app_icon).setOngoing(true).build();if(Build.VERSION.SDK_INT>=29)startForeground(1001,n,android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);else startForeground(1001,n);thread=new HandlerThread("capture");thread.start();handler=new Handler(thread.getLooper());showOverlay();}
 @Override public int onStartCommand(Intent in,int f,int id){if(in==null)return START_NOT_STICKY;int rc=in.getIntExtra("resultCode",-1);Intent data=Build.VERSION.SDK_INT>=33?in.getParcelableExtra("resultData",Intent.class):in.getParcelableExtra("resultData");if(rc!=-1&&data!=null&&projection==null){MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(rc,data);setup();}return START_NOT_STICKY;}
 private void showOverlay(){if(!Settings.canDrawOverlays(this))return;wm=(WindowManager)getSystemService(WINDOW_SERVICE);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.HORIZONTAL);box.setPadding(10,4,6,4);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.argb(235,25,25,25));bg.setCornerRadius(30);box.setBackground(bg);
  TextView title=new TextView(this);title.setText("화면 번역");title.setTextColor(Color.WHITE);title.setTextSize(14);title.setPadding(8,0,10,0);
  status=new TextView(this);status.setText("준비");status.setTextColor(Color.LTGRAY);status.setTextSize(11);status.setPadding(5,0,8,0);
  Button go=new Button(this);go.setText("화면 번역하기");go.setTextSize(12);go.setAllCaps(false);go.setOnClickListener(v->{status.setText("캡처 중…");requested.set(true);});
  Button close=new Button(this);close.setText("×");close.setAllCaps(false);close.setOnClickListener(v->stopSelf());
  box.addView(title);box.addView(status,new LinearLayout.LayoutParams(70,-2));box.addView(go,new LinearLayout.LayoutParams(125,-2));box.addView(close,new LinearLayout.LayoutParams(55,-2));
  WindowManager.LayoutParams lp=new WindowManager.LayoutParams(-2,-2,Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.START;lp.x=20;lp.y=180;
  final float[] down={0,0};final int[] start={0,0};View.OnTouchListener drag=(v,e)->{if(e.getAction()==0){down[0]=e.getRawX();down[1]=e.getRawY();start[0]=lp.x;start[1]=lp.y;return true;}if(e.getAction()==2){lp.x=start[0]+(int)(e.getRawX()-down[0]);lp.y=start[1]+(int)(e.getRawY()-down[1]);wm.updateViewLayout(overlay,lp);return true;}return false;};title.setOnTouchListener(drag);status.setOnTouchListener(drag);overlay=box;wm.addView(overlay,lp);}
 private void setup(){WindowManager x=(WindowManager)getSystemService(WINDOW_SERVICE);DisplayMetrics dm=new DisplayMetrics();x.getDefaultDisplay().getRealMetrics(dm);w=Math.min(dm.widthPixels,1600);h=Math.min(dm.heightPixels,1600);dpi=dm.densityDpi;reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(r->{Image im=null;try{im=r.acquireLatestImage();if(im==null||!requested.compareAndSet(true,false))return;String data=jpeg(im);FrameListener l=listener;if(l!=null)l.onFrame(data);if(status!=null)new Handler(Looper.getMainLooper()).post(()->status.setText("캡처 완료"));}finally{if(im!=null)im.close();}},handler);display=projection.createVirtualDisplay("TextBot",w,h,dpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,handler);}
 private String jpeg(Image im){Image.Plane p=im.getPlanes()[0];ByteBuffer b=p.getBuffer();int stride=p.getPixelStride(),row=p.getRowStride(),pad=row-stride*w;Bitmap bm=Bitmap.createBitmap(w+pad/stride,h,Bitmap.Config.ARGB_8888);bm.copyPixelsFromBuffer(b);Bitmap crop=Bitmap.createBitmap(bm,0,0,w,h);if(crop!=bm)bm.recycle();ByteArrayOutputStream o=new ByteArrayOutputStream();crop.compress(Bitmap.CompressFormat.JPEG,78,o);crop.recycle();return "data:image/jpeg;base64,"+Base64.encodeToString(o.toByteArray(),Base64.NO_WRAP);}
 private void channel(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);n.createNotificationChannel(new NotificationChannel("capture","TextBot 화면 번역",NotificationManager.IMPORTANCE_LOW));}}
 @Override public void onDestroy(){if(wm!=null&&overlay!=null)try{wm.removeView(overlay);}catch(Exception e){}if(display!=null)display.release();if(reader!=null)reader.close();if(projection!=null)projection.stop();if(thread!=null)thread.quitSafely();instance=null;super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}